// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_videocontent.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getVideoContentTVShow = `-- name: GetVideoContentTVShow :many
SELECT id, created_at, delivery_status, states FROM video_content
WHERE tvshow_id=$1 AND season_number=$2
`

type GetVideoContentTVShowParams struct {
	TvshowID     *int64
	SeasonNumber *int32
}

type GetVideoContentTVShowRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	DeliveryStatus int
	States         []byte
}

func (q *Queries) GetVideoContentTVShow(ctx context.Context, arg GetVideoContentTVShowParams) ([]GetVideoContentTVShowRow, error) {
	rows, err := q.db.Query(ctx, getVideoContentTVShow, arg.TvshowID, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVideoContentTVShowRow
	for rows.Next() {
		var i GetVideoContentTVShowRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeliveryStatus,
			&i.States,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoContentsByDeliveryStatus = `-- name: GetVideoContentsByDeliveryStatus :many
SELECT id, created_at, movie_id, tvshow_id, season_number, delivery_status, states FROM video_content
WHERE delivery_status=$1 ORDER BY created_at DESC limit $2
`

type GetVideoContentsByDeliveryStatusParams struct {
	DeliveryStatus int
	Limit          int32
}

func (q *Queries) GetVideoContentsByDeliveryStatus(ctx context.Context, arg GetVideoContentsByDeliveryStatusParams) ([]VideoContent, error) {
	rows, err := q.db.Query(ctx, getVideoContentsByDeliveryStatus, arg.DeliveryStatus, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoContent
	for rows.Next() {
		var i VideoContent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.MovieID,
			&i.TvshowID,
			&i.SeasonNumber,
			&i.DeliveryStatus,
			&i.States,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoContentsMovieID = `-- name: GetVideoContentsMovieID :many
SELECT id, created_at,delivery_status, states FROM video_content
WHERE movie_id=$1
`

type GetVideoContentsMovieIDRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	DeliveryStatus int
	States         []byte
}

func (q *Queries) GetVideoContentsMovieID(ctx context.Context, movieID *int64) ([]GetVideoContentsMovieIDRow, error) {
	rows, err := q.db.Query(ctx, getVideoContentsMovieID, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVideoContentsMovieIDRow
	for rows.Next() {
		var i GetVideoContentsMovieIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeliveryStatus,
			&i.States,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveVideoContent = `-- name: SaveVideoContent :exec
INSERT INTO video_content (id, created_at, movie_id, tvshow_id, season_number, delivery_status, states)
VALUES ($1, $2, $3, $4, $5, $6,$7)
`

type SaveVideoContentParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	MovieID        *int64
	TvshowID       *int64
	SeasonNumber   *int32
	DeliveryStatus int
	States         []byte
}

func (q *Queries) SaveVideoContent(ctx context.Context, arg SaveVideoContentParams) error {
	_, err := q.db.Exec(ctx, saveVideoContent,
		arg.ID,
		arg.CreatedAt,
		arg.MovieID,
		arg.TvshowID,
		arg.SeasonNumber,
		arg.DeliveryStatus,
		arg.States,
	)
	return err
}

const updateVideoContent = `-- name: UpdateVideoContent :one
UPDATE video_content
SET delivery_status=$1
WHERE id=$2
RETURNING id
`

type UpdateVideoContentParams struct {
	DeliveryStatus int
	ID             uuid.UUID
}

func (q *Queries) UpdateVideoContent(ctx context.Context, arg UpdateVideoContentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateVideoContent, arg.DeliveryStatus, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
