--
-- PostgreSQL database dump
--


-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-0ubuntu0.25.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: content_label; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_label (
    created_at timestamp with time zone NOT NULL,
    movie_id bigint,
    tvshow_id bigint,
    season_number integer,
    type_label integer NOT NULL,
    CONSTRAINT content_choice_chk CHECK ((((movie_id IS NOT NULL) AND (tvshow_id IS NULL) AND (season_number IS NULL)) OR ((movie_id IS NULL) AND (tvshow_id IS NOT NULL) AND (season_number IS NOT NULL))))
);


--
-- Name: episodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.episodes (
    tv_show_id bigint NOT NULL,
    season_number integer NOT NULL,
    air_date timestamp with time zone NOT NULL,
    episode_number integer NOT NULL,
    episode_type text,
    name text NOT NULL,
    overview text NOT NULL,
    runtime integer NOT NULL,
    still_id text,
    vote_average real NOT NULL,
    vote_count integer NOT NULL,
    CONSTRAINT episodes_season_number_check CHECK ((season_number >= 0))
);


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images (
    id text NOT NULL,
    w92 text,
    w185 text,
    w342 text,
    original text NOT NULL
);


--
-- Name: mkv_merge; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mkv_merge (
    id uuid NOT NULL,
    idempotency_key text NOT NULL,
    params jsonb NOT NULL,
    status integer NOT NULL,
    error text,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    progress real
);


--
-- Name: mkv_merge_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mkv_merge_logs (
    id bigint NOT NULL,
    merge_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    type integer NOT NULL,
    content text NOT NULL
);


--
-- Name: mkv_merge_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.mkv_merge_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: mkv_merge_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.mkv_merge_logs_id_seq OWNED BY public.mkv_merge_logs.id;


--
-- Name: seasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seasons (
    tv_show_id bigint NOT NULL,
    season_number integer NOT NULL,
    air_date timestamp with time zone NOT NULL,
    episode_count integer NOT NULL,
    name text NOT NULL,
    overview text NOT NULL,
    poster_id text,
    vote_average real NOT NULL,
    CONSTRAINT seasons_season_number_check CHECK ((season_number >= 0))
);


--
-- Name: state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.state (
    id uuid NOT NULL,
    idempotency_key text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    status integer NOT NULL,
    step text NOT NULL,
    type text NOT NULL,
    error text,
    data jsonb,
    fail_data jsonb,
    meta_data jsonb
);


--
-- Name: step_execute_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.step_execute_info (
    id integer NOT NULL,
    state_id uuid NOT NULL,
    start_executed_at timestamp with time zone NOT NULL,
    complete_executed_at timestamp with time zone NOT NULL,
    error text,
    preview_step text NOT NULL,
    next_step text
);


--
-- Name: step_execute_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.step_execute_info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: step_execute_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.step_execute_info_id_seq OWNED BY public.step_execute_info.id;


--
-- Name: tv_shows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tv_shows (
    id bigint NOT NULL,
    name text NOT NULL,
    original_name text NOT NULL,
    overview text NOT NULL,
    poster_id text,
    first_air_date timestamp with time zone NOT NULL,
    vote_average real NOT NULL,
    vote_count integer NOT NULL,
    popularity real NOT NULL,
    backdrop_id text,
    genres text[],
    last_air_date timestamp with time zone NOT NULL,
    number_of_episodes integer NOT NULL,
    number_of_seasons integer NOT NULL,
    origin_country text[],
    status text,
    tagline text NOT NULL,
    type text,
    CONSTRAINT tv_shows_id_check CHECK ((id >= 0)),
    CONSTRAINT tv_shows_number_of_episodes_check CHECK ((number_of_episodes >= 0)),
    CONSTRAINT tv_shows_number_of_seasons_check CHECK ((number_of_seasons >= 0))
);


--
-- Name: video_content; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.video_content (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    movie_id bigint,
    tvshow_id bigint,
    season_number integer,
    delivery_status integer NOT NULL,
    states jsonb,
    CONSTRAINT content_choice_chk CHECK ((((movie_id IS NOT NULL) AND (tvshow_id IS NULL) AND (season_number IS NULL)) OR ((movie_id IS NULL) AND (tvshow_id IS NOT NULL) AND (season_number IS NOT NULL))))
);


--
-- Name: mkv_merge_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mkv_merge_logs ALTER COLUMN id SET DEFAULT nextval('public.mkv_merge_logs_id_seq'::regclass);


--
-- Name: step_execute_info id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_execute_info ALTER COLUMN id SET DEFAULT nextval('public.step_execute_info_id_seq'::regclass);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: mkv_merge_logs mkv_merge_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mkv_merge_logs
    ADD CONSTRAINT mkv_merge_logs_pkey PRIMARY KEY (id);


--
-- Name: mkv_merge mkv_merge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mkv_merge
    ADD CONSTRAINT mkv_merge_pkey PRIMARY KEY (id);


--
-- Name: state state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.state
    ADD CONSTRAINT state_pkey PRIMARY KEY (id);


--
-- Name: step_execute_info step_execute_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_execute_info
    ADD CONSTRAINT step_execute_info_pkey PRIMARY KEY (id);


--
-- Name: tv_shows tv_shows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tv_shows
    ADD CONSTRAINT tv_shows_pkey PRIMARY KEY (id);


--
-- Name: content_label unique_movie_label; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_label
    ADD CONSTRAINT unique_movie_label UNIQUE (movie_id, type_label);


--
-- Name: content_label unique_tvshow_label; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_label
    ADD CONSTRAINT unique_tvshow_label UNIQUE (tvshow_id, season_number, type_label);


--
-- Name: video_content video_content_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.video_content
    ADD CONSTRAINT video_content_pkey PRIMARY KEY (id);


--
-- Name: idx_episodes_tv_show_id_season_number_episode_number; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_episodes_tv_show_id_season_number_episode_number ON public.episodes USING btree (tv_show_id, season_number, episode_number);


--
-- Name: idx_mkv_merge_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_mkv_merge_idempotency_key ON public.mkv_merge USING btree (idempotency_key);


--
-- Name: idx_seasons_tv_show_id_season_number; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_seasons_tv_show_id_season_number ON public.seasons USING btree (tv_show_id, season_number);


--
-- Name: idx_state_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_state_idempotency_key ON public.state USING btree (idempotency_key);


--
-- Name: idx_step_execute_state_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_step_execute_state_id ON public.step_execute_info USING btree (state_id);


--
-- Name: mkv_merge_logs mkv_merge_logs_merge_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mkv_merge_logs
    ADD CONSTRAINT mkv_merge_logs_merge_id_fkey FOREIGN KEY (merge_id) REFERENCES public.mkv_merge(id) ON DELETE CASCADE;


--
-- Name: step_execute_info step_execute_info_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_execute_info
    ADD CONSTRAINT step_execute_info_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.state(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


