// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_mkvmerge.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMergeLogs = `-- name: AddMergeLogs :exec
INSERT INTO mkv_merge_logs (merge_id, created_at, type, content)
VALUES ($1, $2, $3, $4)
`

type AddMergeLogsParams struct {
	MergeID   uuid.UUID
	CreatedAt time.Time
	Type      int
	Content   string
}

func (q *Queries) AddMergeLogs(ctx context.Context, arg AddMergeLogsParams) error {
	_, err := q.db.Exec(ctx, addMergeLogs,
		arg.MergeID,
		arg.CreatedAt,
		arg.Type,
		arg.Content,
	)
	return err
}

const createMkvMerge = `-- name: CreateMkvMerge :exec
INSERT INTO mkv_merge (id, idempotency_key, params, status, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMkvMergeParams struct {
	ID             uuid.UUID
	IdempotencyKey string
	Params         []byte
	Status         int
	CreatedAt      time.Time
}

func (q *Queries) CreateMkvMerge(ctx context.Context, arg CreateMkvMergeParams) error {
	_, err := q.db.Exec(ctx, createMkvMerge,
		arg.ID,
		arg.IdempotencyKey,
		arg.Params,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const deleteLogs = `-- name: DeleteLogs :exec
DELETE from mkv_merge_logs where merge_id=$1
`

func (q *Queries) DeleteLogs(ctx context.Context, mergeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLogs, mergeID)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, idempotency_key, params, status, error, created_at, completed_at, progress FROM mkv_merge
WHERE id=$1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (MkvMerge, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i MkvMerge
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Params,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Progress,
	)
	return i, err
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one
SELECT id, idempotency_key, params, status, error, created_at, completed_at, progress FROM mkv_merge
WHERE idempotency_key=$1
`

func (q *Queries) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (MkvMerge, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, idempotencyKey)
	var i MkvMerge
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Params,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Progress,
	)
	return i, err
}

const getOldestUncompleted = `-- name: GetOldestUncompleted :one
SELECT id, idempotency_key, params, status, error, created_at, completed_at, progress FROM mkv_merge
WHERE completed_at is null
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetOldestUncompleted(ctx context.Context) (MkvMerge, error) {
	row := q.db.QueryRow(ctx, getOldestUncompleted)
	var i MkvMerge
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Params,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Progress,
	)
	return i, err
}

const updateMkvMerge = `-- name: UpdateMkvMerge :one
UPDATE mkv_merge
SET
    status = $1,
    error = COALESCE($2, error),
    completed_at = COALESCE($3, completed_at)
WHERE id = $4
RETURNING id
`

type UpdateMkvMergeParams struct {
	Status      int
	Error       *string
	CompletedAt pgtype.Timestamptz
	ID          uuid.UUID
}

func (q *Queries) UpdateMkvMerge(ctx context.Context, arg UpdateMkvMergeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateMkvMerge,
		arg.Status,
		arg.Error,
		arg.CompletedAt,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProgress = `-- name: UpdateProgress :one
UPDATE mkv_merge
SET progress = $1
WHERE id=$2
RETURNING id
`

type UpdateProgressParams struct {
	Progress *float32
	ID       uuid.UUID
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateProgress, arg.Progress, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
