// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_tvshowlibrary.sql

package db

import (
	"context"
	"time"
)

const getEpisodes = `-- name: GetEpisodes :many
SELECT air_date, episode_number,
       episode_type, name, overview, runtime,
       still_id, vote_average, vote_count
FROM episodes
WHERE tv_show_id = $1 AND season_number = $2
`

type GetEpisodesParams struct {
	TvShowID     int64
	SeasonNumber int
}

type GetEpisodesRow struct {
	AirDate       time.Time
	EpisodeNumber int
	EpisodeType   *string
	Name          string
	Overview      string
	Runtime       int
	StillID       *string
	VoteAverage   float32
	VoteCount     int
}

func (q *Queries) GetEpisodes(ctx context.Context, arg GetEpisodesParams) ([]GetEpisodesRow, error) {
	rows, err := q.db.Query(ctx, getEpisodes, arg.TvShowID, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodesRow
	for rows.Next() {
		var i GetEpisodesRow
		if err := rows.Scan(
			&i.AirDate,
			&i.EpisodeNumber,
			&i.EpisodeType,
			&i.Name,
			&i.Overview,
			&i.Runtime,
			&i.StillID,
			&i.VoteAverage,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImage = `-- name: GetImage :one
SELECT id, w92, w185, w342, original FROM images WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.W92,
		&i.W185,
		&i.W342,
		&i.Original,
	)
	return i, err
}

const getSeasons = `-- name: GetSeasons :many
SELECT air_date, episode_count, name, overview, poster_id, season_number, vote_average
FROM seasons
WHERE tv_show_id = $1
ORDER BY season_number
`

type GetSeasonsRow struct {
	AirDate      time.Time
	EpisodeCount int
	Name         string
	Overview     string
	PosterID     *string
	SeasonNumber int
	VoteAverage  float32
}

func (q *Queries) GetSeasons(ctx context.Context, tvShowID int64) ([]GetSeasonsRow, error) {
	rows, err := q.db.Query(ctx, getSeasons, tvShowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonsRow
	for rows.Next() {
		var i GetSeasonsRow
		if err := rows.Scan(
			&i.AirDate,
			&i.EpisodeCount,
			&i.Name,
			&i.Overview,
			&i.PosterID,
			&i.SeasonNumber,
			&i.VoteAverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTVShow = `-- name: GetTVShow :one
SELECT
    id, name, original_name, overview, poster_id,
    first_air_date, vote_average, vote_count, popularity,
    backdrop_id, genres, last_air_date,
    number_of_episodes, number_of_seasons, origin_country,
    status, tagline, type
FROM tv_shows
WHERE id = $1
`

func (q *Queries) GetTVShow(ctx context.Context, id int64) (TvShow, error) {
	row := q.db.QueryRow(ctx, getTVShow, id)
	var i TvShow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.Overview,
		&i.PosterID,
		&i.FirstAirDate,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Popularity,
		&i.BackdropID,
		&i.Genres,
		&i.LastAirDate,
		&i.NumberOfEpisodes,
		&i.NumberOfSeasons,
		&i.OriginCountry,
		&i.Status,
		&i.Tagline,
		&i.Type,
	)
	return i, err
}

const getTVShows = `-- name: GetTVShows :many
SELECT
    id, name, original_name, overview, poster_id,
    first_air_date, vote_average, vote_count, popularity
FROM tv_shows
ORDER BY popularity DESC
`

type GetTVShowsRow struct {
	ID           int64
	Name         string
	OriginalName string
	Overview     string
	PosterID     *string
	FirstAirDate time.Time
	VoteAverage  float32
	VoteCount    int
	Popularity   float32
}

func (q *Queries) GetTVShows(ctx context.Context) ([]GetTVShowsRow, error) {
	rows, err := q.db.Query(ctx, getTVShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTVShowsRow
	for rows.Next() {
		var i GetTVShowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginalName,
			&i.Overview,
			&i.PosterID,
			&i.FirstAirDate,
			&i.VoteAverage,
			&i.VoteCount,
			&i.Popularity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEpisode = `-- name: SaveEpisode :exec
INSERT INTO episodes (
    tv_show_id, season_number, air_date, episode_number,
    episode_type, name, overview, runtime,
    still_id, vote_average, vote_count
) VALUES ($1, $2, $3, $4,
          $5, $6, $7, $8, $9,
          $10, $11)
`

type SaveEpisodeParams struct {
	TvShowID      int64
	SeasonNumber  int
	AirDate       time.Time
	EpisodeNumber int
	EpisodeType   *string
	Name          string
	Overview      string
	Runtime       int
	StillID       *string
	VoteAverage   float32
	VoteCount     int
}

func (q *Queries) SaveEpisode(ctx context.Context, arg SaveEpisodeParams) error {
	_, err := q.db.Exec(ctx, saveEpisode,
		arg.TvShowID,
		arg.SeasonNumber,
		arg.AirDate,
		arg.EpisodeNumber,
		arg.EpisodeType,
		arg.Name,
		arg.Overview,
		arg.Runtime,
		arg.StillID,
		arg.VoteAverage,
		arg.VoteCount,
	)
	return err
}

const saveImage = `-- name: SaveImage :exec
INSERT INTO images (id, w92, w185, w342, original)
VALUES ($1, $2, $3, $4, $5)
`

type SaveImageParams struct {
	ID       string
	W92      *string
	W185     *string
	W342     *string
	Original string
}

// ----------------------------------------------------------------------------------------------------------------------
func (q *Queries) SaveImage(ctx context.Context, arg SaveImageParams) error {
	_, err := q.db.Exec(ctx, saveImage,
		arg.ID,
		arg.W92,
		arg.W185,
		arg.W342,
		arg.Original,
	)
	return err
}

const saveSeason = `-- name: SaveSeason :exec
INSERT INTO seasons (
    tv_show_id, season_number, air_date, episode_count,
    name, overview, poster_id, vote_average
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveSeasonParams struct {
	TvShowID     int64
	SeasonNumber int
	AirDate      time.Time
	EpisodeCount int
	Name         string
	Overview     string
	PosterID     *string
	VoteAverage  float32
}

func (q *Queries) SaveSeason(ctx context.Context, arg SaveSeasonParams) error {
	_, err := q.db.Exec(ctx, saveSeason,
		arg.TvShowID,
		arg.SeasonNumber,
		arg.AirDate,
		arg.EpisodeCount,
		arg.Name,
		arg.Overview,
		arg.PosterID,
		arg.VoteAverage,
	)
	return err
}

const saveTVShow = `-- name: SaveTVShow :exec
INSERT INTO tv_shows (
    id, name, original_name, overview, poster_id,
    first_air_date, vote_average, vote_count, popularity,
    backdrop_id, genres, last_air_date,
    number_of_episodes, number_of_seasons, origin_country,
    status, tagline, type
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
          $9, $10, $11, $12, $13, $14,
          $15, $16, $17, $18)
`

type SaveTVShowParams struct {
	ID               int64
	Name             string
	OriginalName     string
	Overview         string
	PosterID         *string
	FirstAirDate     time.Time
	VoteAverage      float32
	VoteCount        int
	Popularity       float32
	BackdropID       *string
	Genres           []string
	LastAirDate      time.Time
	NumberOfEpisodes int
	NumberOfSeasons  int
	OriginCountry    []string
	Status           *string
	Tagline          string
	Type             *string
}

func (q *Queries) SaveTVShow(ctx context.Context, arg SaveTVShowParams) error {
	_, err := q.db.Exec(ctx, saveTVShow,
		arg.ID,
		arg.Name,
		arg.OriginalName,
		arg.Overview,
		arg.PosterID,
		arg.FirstAirDate,
		arg.VoteAverage,
		arg.VoteCount,
		arg.Popularity,
		arg.BackdropID,
		arg.Genres,
		arg.LastAirDate,
		arg.NumberOfEpisodes,
		arg.NumberOfSeasons,
		arg.OriginCountry,
		arg.Status,
		arg.Tagline,
		arg.Type,
	)
	return err
}
