server:
  host: "localhost"
  http_port: 8080
  grpc_port: 8181
  max_send_message_length: 2147483647
  max_receive_message_length: 63554432
  shutdown_timeout: 3

the_movie_db:
  api_key: ""

rutracker:
  username: ""
  password: ""
  cookie_dir: "./cookies"

qbittorrent:
  username: ""
  password: ""
  cookie_dir: "./cookies"
  api_url: ""

emby:
  api_key: ""
  api_url: ""

sqlite:
  sqlite_dsn: ""

delivery:
  base_path: "/nfs"
  tv_show_torrent_save_path: "/downloads"
  tv_show_media_save_tv_shows_path: "/tvshows"
  user_group: "nas"