// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentLabel struct {
	CreatedAt    time.Time
	MovieID      *int64
	TvshowID     *int64
	SeasonNumber *int32
	TypeLabel    int
}

type Episode struct {
	TvShowID      int64
	SeasonNumber  int
	AirDate       time.Time
	EpisodeNumber int
	EpisodeType   *string
	Name          string
	Overview      string
	Runtime       int
	StillID       *string
	VoteAverage   float32
	VoteCount     int
}

type GooseDbVersion struct {
	ID        int
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type Image struct {
	ID       string
	W92      *string
	W185     *string
	W342     *string
	Original string
}

type MkvMerge struct {
	ID             uuid.UUID
	IdempotencyKey string
	Params         []byte
	Status         int
	Error          *string
	CreatedAt      time.Time
	CompletedAt    pgtype.Timestamptz
	Progress       *float32
}

type MkvMergeLog struct {
	ID        int64
	MergeID   uuid.UUID
	CreatedAt time.Time
	Type      int
	Content   string
}

type Season struct {
	TvShowID     int64
	SeasonNumber int
	AirDate      time.Time
	EpisodeCount int
	Name         string
	Overview     string
	PosterID     *string
	VoteAverage  float32
}

type State struct {
	ID             uuid.UUID
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Status         int
	Step           string
	Type           string
	Error          *string
	Data           []byte
	FailData       []byte
	MetaData       []byte
}

type StepExecuteInfo struct {
	ID                 int
	StateID            uuid.UUID
	StartExecutedAt    time.Time
	CompleteExecutedAt time.Time
	Error              *string
	PreviewStep        string
	NextStep           *string
}

type TvShow struct {
	ID               int64
	Name             string
	OriginalName     string
	Overview         string
	PosterID         *string
	FirstAirDate     time.Time
	VoteAverage      float32
	VoteCount        int
	Popularity       float32
	BackdropID       *string
	Genres           []string
	LastAirDate      time.Time
	NumberOfEpisodes int
	NumberOfSeasons  int
	OriginCountry    []string
	Status           *string
	Tagline          string
	Type             *string
}

type VideoContent struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	MovieID        *int64
	TvshowID       *int64
	SeasonNumber   *int32
	DeliveryStatus int
	States         []byte
}
