// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_labels.sql

package db

import (
	"context"
	"time"
)

const deleteLabelMovieID = `-- name: DeleteLabelMovieID :one
DELETE FROM content_label
WHERE movie_id=$1
RETURNING movie_id
`

func (q *Queries) DeleteLabelMovieID(ctx context.Context, movieID *int64) (*int64, error) {
	row := q.db.QueryRow(ctx, deleteLabelMovieID, movieID)
	var movie_id *int64
	err := row.Scan(&movie_id)
	return movie_id, err
}

const deleteLabelTVShow = `-- name: DeleteLabelTVShow :one
DELETE FROM content_label
WHERE tvshow_id=$1 AND season_number=$2
RETURNING tvshow_id, season_number
`

type DeleteLabelTVShowParams struct {
	TvshowID     *int64
	SeasonNumber *int32
}

type DeleteLabelTVShowRow struct {
	TvshowID     *int64
	SeasonNumber *int32
}

func (q *Queries) DeleteLabelTVShow(ctx context.Context, arg DeleteLabelTVShowParams) (DeleteLabelTVShowRow, error) {
	row := q.db.QueryRow(ctx, deleteLabelTVShow, arg.TvshowID, arg.SeasonNumber)
	var i DeleteLabelTVShowRow
	err := row.Scan(&i.TvshowID, &i.SeasonNumber)
	return i, err
}

const getLabelsMovieID = `-- name: GetLabelsMovieID :many
SELECT created_at, type_label FROM content_label
WHERE movie_id=$1
`

type GetLabelsMovieIDRow struct {
	CreatedAt time.Time
	TypeLabel int
}

func (q *Queries) GetLabelsMovieID(ctx context.Context, movieID *int64) ([]GetLabelsMovieIDRow, error) {
	rows, err := q.db.Query(ctx, getLabelsMovieID, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLabelsMovieIDRow
	for rows.Next() {
		var i GetLabelsMovieIDRow
		if err := rows.Scan(&i.CreatedAt, &i.TypeLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabelsTVShow = `-- name: GetLabelsTVShow :many
SELECT created_at, type_label FROM content_label
WHERE tvshow_id=$1 AND season_number=$2
`

type GetLabelsTVShowParams struct {
	TvshowID     *int64
	SeasonNumber *int32
}

type GetLabelsTVShowRow struct {
	CreatedAt time.Time
	TypeLabel int
}

func (q *Queries) GetLabelsTVShow(ctx context.Context, arg GetLabelsTVShowParams) ([]GetLabelsTVShowRow, error) {
	rows, err := q.db.Query(ctx, getLabelsTVShow, arg.TvshowID, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLabelsTVShowRow
	for rows.Next() {
		var i GetLabelsTVShowRow
		if err := rows.Scan(&i.CreatedAt, &i.TypeLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLabel = `-- name: SaveLabel :exec
INSERT INTO content_label (movie_id, tvshow_id, season_number, created_at, type_label)
VALUES ($1, $2, $3, $4, $5)
`

type SaveLabelParams struct {
	MovieID      *int64
	TvshowID     *int64
	SeasonNumber *int32
	CreatedAt    time.Time
	TypeLabel    int
}

func (q *Queries) SaveLabel(ctx context.Context, arg SaveLabelParams) error {
	_, err := q.db.Exec(ctx, saveLabel,
		arg.MovieID,
		arg.TvshowID,
		arg.SeasonNumber,
		arg.CreatedAt,
		arg.TypeLabel,
	)
	return err
}
